# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BDA_partial_sort <- function(x, n) {
    .Call('_BehavioralDataAnalysis_BDA_partial_sort', PACKAGE = 'BehavioralDataAnalysis', x, n)
}

