---
title: "Generating the data for the AirCnC M&M exercises"
output: html_notebook
---

```{r}
library(tidyverse)
library(psych)
library(rstudioapi) #To load data from local folder

### Setting the working directory to the parent folder of this script (Rstudio only)
sourceDir <- rstudioapi::getActiveDocumentContext()$path %>% str_extract("^.+/")
setwd(sourceDir)

set.seed(1)
options(scipen=10)
```

# Creating the data

```{r}
N <- 1e6

dat <- tibble(
  period = rep(0:1, N/2),
  income = rlnorm(N) * 0.75*1e5,
  ad = ifelse(runif(N)<= 0.2 & period == 1, 1, 0),
  val_mm = (income + 5e3*ad-5e5)/1e5,
  prob_mm = logistic(val_mm),
  mm = ifelse(runif(N)<= prob_mm, 1, 0),
  val_bkd = (income - 1e4*mm - 1e5)/1e5,
  prob_bkd = logistic(val_bkd),
  bkd = ifelse(runif(N)<= prob_bkd, 1, 0),
  bkd_mm = bkd * mm
)
summary(dat)
```
# Filtering the variables we want to keep
```{r}
output_dat <- dat %>%
  select(period, income, ad, mm, bkd) %>%
  mutate(income = round(income, 0))
```
# Saving the data in a file
```{r}
write_csv(output_dat, "AirCnC_MnM_exercises_data.csv")
```