---
title: "Chapter 10: Cluster Randomization and Hierarchical Modeling"
output: html_notebook
---

This is the [R Markdown](http://rmarkdown.rstudio.com) Notebook for chapter 10.

# Data and libraries

```{r}
# Common libraries
suppressMessages(suppressWarnings(library(tidyverse)))
library(rstudioapi) #To load data from local folder
library(ggpubr) #To generate multi-plots
library(BehavioralDataAnalysis)

# Chapter-specific libraries
library(lme4) # For hierarchical modeling
library(lmerTest) # For additional diagnostics of hierarchical modeling
install_github("d4ndo/binaryLogic")
library(binaryLogic) # For function as.binary()

### Setting the working directory to the parent folder of this script (Rstudio only)
sourceDir <- rstudioapi::getActiveDocumentContext()$path %>% str_extract("^.+/")
setwd(sourceDir)

set.seed(1234)
options(scipen=10)
```

```{r}
#Reading the data
hist_data <- read_csv("chap10-historical_data.csv")
exp_data <- read_csv("chap10-experimental_data.csv")

#Reformating the data
hist_data <- hist_data %>%
  mutate(center_ID = factor(center_ID)) %>%
  mutate(rep_ID = factor(rep_ID)) %>%
  mutate(reason = factor(reason)) %>%
  select(-M6Spend)
exp_data <- exp_data %>%
  # Setting the factor variables to have the same levels as their counterparts
  # in the first dataset
  mutate(center_ID = factor(center_ID, levels = levels(hist_data$center_ID)),
         rep_ID = factor(rep_ID, levels = levels(hist_data$rep_ID)),
         reason = factor(reason, levels = levels(hist_data$reason)),
         grp = factor(grp)) %>%
  select(-M6Spend)

```

# Introduction to hierarchical modeling 

```{r}
hlm_mod <- lmer(data=hist_data, call_CSAT ~ reason + age + (1|center_ID))
summary(hlm_mod)
```

```{r}
hist_data %>%
  group_by(center_ID)%>%
  summarize(call_CSAT = mean(call_CSAT)) %>%
  summarize(sd = sd(call_CSAT))
```

```{r}
hist_data %>%
  group_by(rep_ID) %>%
  summarise(call_CSAT = mean(call_CSAT)) %>%
  summarise(sd = sd(call_CSAT))
```

```{r}
hlm_mod2 <- lmer(data=hist_data,
                 call_CSAT ~ reason + age + (1|center_ID/rep_ID),
                 control = lmerControl(optimizer ="Nelder_Mead"))
summary(hlm_mod2)
```

# Determining random assignment and sample size/power

## Stratificed random assignment

```{r}
# Aggregating data to center level
center_data <- hist_data %>%
  group_by(center_ID) %>%
    summarise(nreps = n_distinct(rep_ID),
              avg_call_CSAT = mean(call_CSAT), 
              avg_age = mean(age),
              pct_reason_pmt = sum(reason == 'payment')/n()) %>%
    ungroup()
  
```


```{r}
center_pairs <- pair(center_data, id = "center_ID")
center_pairs
```

## Power analysis

```{r}
# Metric function
hlm_metric_fun <- function(dat){
  # Estimating treatment coefficient with hierarchical regression
  metric = tryCatch(
    expr = {hlm_mod <- lmer(data=dat, 
                  call_CSAT ~ reason + age + grp + (1|center_ID/rep_ID)
                  ,control = lmerControl(optimizer ="Nelder_Mead"))
    fixef(hlm_mod)["grptreat"]}, 
    error = function(e){
      print('there was an error', '\n')
      NA})
  # Uncomment following line for debugging
  #cat('hlm will return: ', metric, '\n')
  return(metric)
}
```

```{r}
# Decision function
decision_fun <- function(dat, metric_fun, B = 100, conf.level = 0.9){
  boot_ci_values <- boot_ci(dat, metric_fun, B = B, conf.level = conf.level)
  decision <- ifelse(boot_ci_values[1]>0,1,0)
  return(decision)
}
```

```{r}
# Function creating a permutation from an integer (starting at zero)
permutation_gen_fun <- function(i, stratified_pairs){
  Npairs <- nrow(stratified_pairs)
  bin_str <- as.binary(i, n=Npairs)
  idx <- matrix(c(1:Npairs, bin_str), nrow = Npairs)
  idx[,2] <- idx[,2] + 1
  treat <- stratified_pairs[idx]
  return(treat)
}
permutation_gen_fun(0, center_pairs)
permutation_gen_fun(15, center_pairs)
```

```{r}
# Power simulation function 
power_sim_fun <- function(dat, metric_fun, Nexp = 1000, eff_size = 0, B = 20, conf.level = 0.9){
  #Extract the stratified pairs
  stratified_pairs <- pair(center_data, id = "center_ID")
  Npairs <- nrow(stratified_pairs)
  Nmonths <- length(unique(dat$month))
  Nperm <- 2^Npairs
  Nsim <- Nmonths * Nperm
  
  power_list <- vector(mode = "list", length = Nsim)
  i <- 1
  for(m in unique(dat$month)){
    #Sample down the data
    sample_data <- filter(dat, month==m) %>% dplyr::group_by(rep_ID) %>%
      slice_sample(n = Nexp) %>% dplyr::ungroup()
    
    for(perm in 0:(Nperm-1)){
      treat <- permutation_gen_fun(perm, stratified_pairs)
      
      sim_data <- sample_data %>%
        mutate(grp = ifelse(center_ID %in% treat, 'treat', 'ctrl')) %>%
        mutate(grp = as.factor(grp))
      
      sim_data <- sim_data %>%
        mutate(call_CSAT = ifelse(grp == 'treat', 
                                  call_CSAT + eff_size, call_CSAT)) %>%
        #Ensuring that call CSAT remains between 0 and 10
        mutate(call_CSAT = pmax(call_CSAT, 0)) %>%
        mutate(call_CSAT = pmin(call_CSAT, 10))
      
      # Calculate the decision
      power_list[[i]] <- decision_fun(sim_data, metric_fun, B = B, conf.level = conf.level)
      i <- i + 1
    }
  }
  power <- mean(unlist(power_list))
  return(power)
}
p <- power_sim_fun(hist_data, hlm_metric_fun, Nexp = 230000, eff_size = 0, B = 40, conf.level = 0.9)
p
```

```{r}
#Loading the saved output from the simulations
sig_dat <- read_csv("sig_dat.csv")

viz_fun10.3 <- function(sig_dat){
  ggplot(sig_dat %>% filter(conf.level==0.90) %>% arrange(lower_bound), aes(y=1:96)) + 
    geom_linerange(aes(xmin=lower_bound, xmax=upper_bound)) +
    geom_vline(xintercept = 0, col='red') +
    ylab("Ordered confidence intervals") +
    xlab("Coefficient for experimental treatment") + theme_classic()
}
viz_fun10.3(sig_dat)
```


```{r}
#Loading the saved output from the simulations
ES_dat <- read_csv("ES_dat.csv")

viz_fun9.4 <- function(ES_dat){
  power_dat <- ES_dat %>%
  group_by(eff_size)  %>%
  summarise(power = sum(lower_bound > 0)/n()) %>%
  ungroup() %>%
  rbind(sig_dat %>% filter(conf.level == 0.90) %>%
          group_by(eff_size)  %>%
          summarise(power = sum(lower_bound > 0)/n()))
  
  p <- ggplot(power_dat, aes(x = eff_size, y = power)) +
     geom_hline(yintercept = 0.80, col = 'red') + theme_classic() +
    geom_point() + ylim(c(0,1)) + xlab("effect size") +
    geom_line(data = power_dat %>% filter(eff_size != 0)) + 
    geom_label(x=0.03, y=0.555, label="significance")
  return(p)
}
viz_fun9.4(ES_dat )
```


```{r}
viz_fun10.5 <- function(ES_dat){
  power_dat2 <- ES_dat %>%
  group_by(eff_size)  %>%
  summarise(power = sum(lower_bound > 0.25)/n()) %>%
  ungroup() %>%
  rbind(sig_dat %>% filter(conf.level == 0.90) %>%
          group_by(eff_size)  %>%
          summarise(power = sum(lower_bound > 0.25)/n()))
  p <- ggplot(power_dat2, aes(x = eff_size, y = power)) +
    geom_point() + ylim(c(0,1)) + xlab("effect size") +
    geom_line(data = power_dat2 %>% filter(eff_size != 0)) + 
    geom_label(x=0.035, y=0.325, label="significance") +
    geom_hline(yintercept = 0.80, col = 'red') +
    theme_classic()
  return(p)
}
viz_fun10.5(ES_dat)
```
# Analyzing the experiment

```{r}
coeff <- hlm_metric_fun(exp_data)
print(coeff)

hlm_ci_values <- boot_ci(exp_data, hlm_metric_fun)
print(hlm_cI_values)

```